name: Build deb packages
concurrency:
  group: build-packages-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.devcontainer/**'
      - '*.md'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-deb-packages:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.os }}-${{ matrix.arch }}-pg${{ matrix.pg_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu22.04, ubuntu24.04, deb11, deb12]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
        pg_version:
          - 16
          - 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract and Format Default Version
        id: extract_version
        run: |
          DOCUMENTDB_VERSION=$(grep -E "^default_version" pg_documentdb_core/documentdb_core.control | sed -E "s/.*'([0-9]+\.[0-9]+-[0-9]+)'.*/\1/")
          DOCUMENTDB_VERSION=$(echo $DOCUMENTDB_VERSION | sed "s/-/./g")
          echo "Extracted Version: $DOCUMENTDB_VERSION"
          echo "DOCUMENTDB_VERSION=$DOCUMENTDB_VERSION" >> $GITHUB_ENV

      - name: Build Debian Package
        run: |
          ./packaging/build_packages.sh --os ${{ matrix.os }} --pg ${{ matrix.pg_version }} --version ${{ env.DOCUMENTDB_VERSION }}

      - name: Upload Debian Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive-${{ matrix.os }}-${{ matrix.arch }}-pg${{ matrix.pg_version }}-documentdb-${{ env.DOCUMENTDB_VERSION }}
          path: packaging/*.deb
          retention-days: 7
          if-no-files-found: error
          compression-level: 0

      - name: Install GitHub CLI manually
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Upload to GitHub Release (excluding dbgsym packages)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Find all .deb files excluding ones with -dbgsym_ in the name
          files=$(find packaging -type f -name "*.deb" ! -name "*-dbgsym_*.deb")
          if [ -z "$files" ]; then
            echo "No .deb packages (excluding dbgsym) found to upload."
            exit 1
          fi
          gh release upload "${{ github.ref_name }}" $files --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
